easy_admin:
    site_name: IT's Comp
    design:
        assets:
            css:
                - 'admin.css'
        menu:
            - { entity: User, icon: user }
            - { entity: Employee, icon: user-tie }
            - { entity: Customer, icon: user-friends }
            - { entity: Task, icon: tasks }
            - { entity: TaskType, icon: toolbox }
            - { entity: ServiceRequest, icon: tools }
            - { entity: CMS, icon: clipboard }
    entities:
        User:
            class: App\Entity\User
            list:
                fields:
                    - { property: email, type: email }
                    - { property: enabled, type: toggle }
                sort: [email, ASC]
                filters: [email, enabled]
            form:
                fields:
                    - email
                    - enabled

        Employee:
            class: App\Entity\Employee
            list:
                fields:
                    - { property: lastName, type: string }
                    - { property: firstName, type: string }
                    - { property: businessNumber, type: string }
                    - { property: id, label: ID Użytkownika, type_options: App\Entity\User }
                sort: [lastName, ASC]
            form:
                fields:
                    - firstName
                    - lastName
                    - businessNumber
                    - user


        Customer:
            class: App\Entity\Customer
            list:
                fields:
                    - lastName
                    - firstName
                    - phone
                    - { property: id, label: ID Użytkownika, type_options: App\Entity\User }
                sort: [lastName, ASC]


        Task:
            class: App\Entity\Task
            list:
                fields:
                    - { property: id, type: integer }
                    - { property: priority, type: integer }
                    - { property: inProgress, type: toggle }
                    - { property: taskType, label: Typ zadania }
                    - { property: serviceRequest, label: Zgłoszenie, type_options: App\Entity\ServiceRequest }
                sort: [id, ASC]
            form:
                fields:
                    - priority
                    - taskType
                    - inProgress
                    - property: serviceRequest
                      type_options:
                          query_builder: App\Repository\ServiceRequestRepository::available


        TaskType:
            class: App\Entity\TaskType
            list:
                fields:
                    - { property: id, type: integer }
                    - name
                    - cost
                sort: [id, ASC]
            form:
                fields:
                    - name
                    - cost


        ServiceRequest:
            class: App\Entity\ServiceRequest
            list:
                fields:
                    - { property: id, type: integer }
                    - subject
                    - proposedDeliveryTime
                    - task
                    - employee
                    - customer
                sort: [id, ASC]
                filters: [subject, task, employee]
            form:
                fields:
                    - subject
                    - proposedDeliveryTime
                    - task
                    - employee


        CMS:
            class: App\Entity\CMS
            list:
                fields:
                    - { property: id, type: integer }
                    - attribute
                    - value
                    - active
                sort: [id, ASC]
            form:
                fields:
                    - attribute
                    - value
                    - active

