#USER
api.users.register:
    path: /users/register
    controller: App\Controller\UserController::register
    methods: POST

api.users.get_all:
    path: /users
    controller: App\Controller\UserController:getUsers
    methods: GET

api.users.confirm:
    path: /users/confirm/{token}
    controller: App\Controller\UserController:confirm
    methods: GET

#CMS
api.cms.create:
    path: /cms
    controller: App\Controller\CMSController:create
    methods: POST

api.cms.get:
    path: /cms
    controller: App\Controller\CMSController:list
    methods: GET

api.cms.update:
    path: /cms
    controller: App\Controller\CMSController:update
    methods: PUT

#TASK-TYPE
api.task-type.create:
    path: /task-types
    controller: App\Controller\TaskTypeController:create
    methods: POST