#USER
api.users.register:
    path: /users/register
    controller: App\Controller\UserController::register
    methods: [POST, OPTIONS]

api.users.get_all:
    path: /users
    controller: App\Controller\UserController:getUsers
    methods: GET

api.users.confirm:
    path: /users/confirm/{token}
    controller: App\Controller\UserController:confirm
    methods: GET

#CMS
api.cms.create:
    path: /cms
    controller: App\Controller\CMSController:create
    methods: [POST, OPTIONS]

api.cms.get:
    path: /cms
    controller: App\Controller\CMSController:list
    methods: GET

api.cms.get_active:
    path: /cms/active
    controller: App\Controller\CMSController:listActive
    methods: GET

api.cms.update:
    path: /cms
    controller: App\Controller\CMSController:update
    methods: [PUT, OPTIONS]

#TASK-TYPE
api.task-type.create:
    path: /task-types
    controller: App\Controller\TaskTypeController:create
    methods: [POST, OPTIONS]

api.task-type.list:
    path: /task-types
    controller: App\Controller\TaskTypeController:list
    methods: GET

#TASKS
api.tasks.create:
    path: /tasks
    controller: App\Controller\TaskController:create
    methods: [POST, OPTIONS]

api.tasks.list:
    path: /tasks
    controller: App\Controller\TaskController:list
    methods: GET

#EMPLOYEE
api.employee.create:
    path: /employees
    controller: App\Controller\EmployeeController:create
    methods: [POST, OPTIONS]

api.employee.list:
    path: /employees
    controller: App\Controller\EmployeeController:list
    methods: GET

#CUSTOMER
api.customer.create:
    path: /customers
    controller: App\Controller\CustomerController:create
    methods: [POST, OPTIONS]

#SERVICE-REQUEST
api.service-requests.create:
    path: /service-requests
    controller: App\Controller\ServiceRequestController:create
    methods: [POST, OPTIONS]

api.service-requests.list:
    path: /service-requests
    controller: App\Controller\ServiceRequestController:list
    methods: GET

api.service-requests.list_by_user:
    path: /service-requests/users
    controller: App\Controller\ServiceRequestController:listByUser
    methods: GET
